#!/usr/bin/env bash
#
# Compiles circuits/delivery.circom and runs a Groth16 trusted setup, then
# exports:
#
#   src/Verifier.sol          — the on-chain verifier (CHECKED IN)
#   circuits/build/*          — proving key, witness calculator, vkey (gitignored)
#
# ############################################################################
# # DEMO-GRADE SETUP — NOT A PRODUCTION CEREMONY.                            #
# #                                                                          #
# # This script generates the powers-of-tau and the circuit-specific phase-2  #
# # contribution locally, on one machine, with entropy this script supplies   #
# # itself. Whoever runs it therefore knows the toxic waste and could forge   #
# # proofs for this circuit at will.                                          #
# #                                                                          #
# # That is fine for a Base Sepolia demo and unacceptable for real value. A   #
# # production deployment needs a multi-party ceremony (e.g. a Perpetual      #
# # Powers of Tau file plus independent phase-2 contributors) where no single #
# # participant sees all the randomness.                                      #
# ############################################################################
#
# NOTE: re-running this script performs a FRESH Groth16 setup, which produces a
# different verification key and therefore a different src/Verifier.sol. The
# checked-in fixture proofs under test/fixtures/ were generated against the
# previous key and will no longer verify. After re-running, regenerate them:
#
#   ./scripts/prove.sh 12345 0 && cp circuits/build/proofs/0/release-args.json \
#       test/fixtures/delivery-proof-escrow0.json
#   ./scripts/prove.sh 12345 1 && cp circuits/build/proofs/1/release-args.json \
#       test/fixtures/delivery-proof-escrow1.json
#
# `forge test` will fail loudly if you forget, so this cannot go unnoticed.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

CIRCUIT_NAME="delivery"
CIRCUIT_SRC="circuits/${CIRCUIT_NAME}.circom"
BUILD_DIR="circuits/build"

# Size of the powers-of-tau. 2^12 constraints is comfortably above what the
# two Poseidon hashes in delivery.circom need.
PTAU_POWER=12

# circomlib ships its templates here once `npm install` has run.
CIRCOMLIB_DIR="node_modules/circomlib/circuits"

SNARKJS="npx --no-install snarkjs"

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v circom >/dev/null 2>&1 || die "circom not found. Install it: https://docs.circom.io/getting-started/installation/"
command -v npx >/dev/null 2>&1 || die "npx not found. Install Node.js 20+."
[ -d "$CIRCOMLIB_DIR" ] || die "circomlib missing. Run: npm install"
[ -f "$CIRCUIT_SRC" ] || die "circuit source not found at $CIRCUIT_SRC"

mkdir -p "$BUILD_DIR"

log "Compiling $CIRCUIT_SRC"
circom "$CIRCUIT_SRC" \
    --r1cs --wasm --sym \
    -l "$CIRCOMLIB_DIR" \
    -o "$BUILD_DIR"

log "Circuit info"
$SNARKJS r1cs info "$BUILD_DIR/${CIRCUIT_NAME}.r1cs"

PTAU_FINAL="$BUILD_DIR/pot${PTAU_POWER}_final.ptau"
if [ -f "$PTAU_FINAL" ]; then
    log "Reusing existing powers-of-tau at $PTAU_FINAL"
else
    log "Powers of tau: ceremony start (DEMO ENTROPY — see header)"
    $SNARKJS powersoftau new bn128 "$PTAU_POWER" "$BUILD_DIR/pot_0000.ptau" -v

    log "Powers of tau: contribution 1"
    $SNARKJS powersoftau contribute \
        "$BUILD_DIR/pot_0000.ptau" "$BUILD_DIR/pot_0001.ptau" \
        --name="zk-escrow demo contribution" -v \
        -e="zk-escrow demo entropy, not a real ceremony"

    log "Powers of tau: phase 2 preparation"
    $SNARKJS powersoftau prepare phase2 \
        "$BUILD_DIR/pot_0001.ptau" "$PTAU_FINAL" -v
fi

log "Groth16 setup"
$SNARKJS groth16 setup \
    "$BUILD_DIR/${CIRCUIT_NAME}.r1cs" \
    "$PTAU_FINAL" \
    "$BUILD_DIR/${CIRCUIT_NAME}_0000.zkey"

log "Phase 2 contribution (DEMO ENTROPY — see header)"
$SNARKJS zkey contribute \
    "$BUILD_DIR/${CIRCUIT_NAME}_0000.zkey" \
    "$BUILD_DIR/${CIRCUIT_NAME}_final.zkey" \
    --name="zk-escrow demo phase2" -v \
    -e="zk-escrow demo phase2 entropy, not a real ceremony"

log "Exporting verification key"
$SNARKJS zkey export verificationkey \
    "$BUILD_DIR/${CIRCUIT_NAME}_final.zkey" \
    "$BUILD_DIR/verification_key.json"

log "Exporting src/Verifier.sol"
$SNARKJS zkey export solidityverifier \
    "$BUILD_DIR/${CIRCUIT_NAME}_final.zkey" \
    "$BUILD_DIR/Verifier.sol"

# snarkjs emits a floating pragma and no SPDX tag. Pin both so the contract
# builds under the same solc as the rest of src/ and Slither stays quiet.
{
    echo "// SPDX-License-Identifier: GPL-3.0"
    echo "// AUTOGENERATED BY scripts/build-circuit.sh — DO NOT EDIT BY HAND."
    echo "// Regenerate with: ./scripts/build-circuit.sh"
    sed -e 's|^// SPDX-License-Identifier:.*$||' \
        -e 's|^pragma solidity .*;$|pragma solidity 0.8.28;|' \
        "$BUILD_DIR/Verifier.sol"
} > src/Verifier.sol

log "Done."
echo
echo "  Checked in:  src/Verifier.sol"
echo "  Gitignored:  $BUILD_DIR/${CIRCUIT_NAME}_final.zkey"
echo "               $BUILD_DIR/${CIRCUIT_NAME}_js/${CIRCUIT_NAME}.wasm"
echo "               $BUILD_DIR/verification_key.json"
echo
echo "  Next: ./scripts/prove.sh <secret> <escrowId>"
