// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

/// @title IVerifier
/// @notice Minimal surface of the Groth16 verifier generated by snarkjs into
///         `src/Verifier.sol` (see `scripts/build-circuit.sh`).
/// @dev The three public signals are, in circom's ordering (outputs first, then
///      declared public inputs):
///        input[0] = nullifier   (circuit output, binds secret to escrowId)
///        input[1] = commitment  (Poseidon(secret), stored on the escrow)
///        input[2] = escrowId    (the escrow the proof is spent against)
interface IVerifier {
    /// @notice Verifies a Groth16 proof over the delivery circuit.
    /// @param _pA First proof element.
    /// @param _pB Second proof element.
    /// @param _pC Third proof element.
    /// @param _pubSignals Public signals: [nullifier, commitment, escrowId].
    /// @return True if the proof is valid for the given public signals.
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[3] calldata _pubSignals
    ) external view returns (bool);
}
